/**
 * Bancos fijos de preguntas y frases — rotan de forma determinística por
 * fecha (mismo índice para todos, mismo día) en vez de guardarse en la base
 * de datos. No requiere administración ni servicios externos.
 */
export const PREGUNTAS_DEL_DIA: string[] = [
  '¿Qué comida elegirías para toda la vida?',
  '¿Cuál fue tu primer trabajo?',
  '¿Qué película recomiendas sin dudar?',
  '¿Perro o gato?',
  '¿Playa o montaña?',
  '¿Cuál es tu serie favorita del momento?',
  '¿Qué app no puede faltar en tu celular?',
  '¿Café o té?',
  '¿Cuál es tu hora favorita del día para trabajar?',
  '¿Qué canción no puede faltar en tu playlist?',
  '¿Cuál fue el último libro que leíste?',
  '¿Qué superpoder te gustaría tener?',
  '¿Cuál es tu snack favorito en la oficina?',
  '¿Prefieres trabajar en silencio o con música?',
  '¿Qué destino quieres visitar antes de que termine el año?',
  '¿Cuál es tu emoji más usado?',
  '¿Madrugador o nocturno?',
  '¿Cuál fue tu materia favorita en la escuela?',
  '¿Qué deporte te gustaría aprender?',
  '¿Cuál es tu comida dominicana favorita?',
  '¿Qué videojuego marcó tu infancia?',
  '¿Prefieres pedir delivery o cocinar?',
  '¿Cuál es tu meme favorito de todos los tiempos?',
  '¿Qué habilidad te gustaría dominar este año?',
  '¿Cuál es tu forma favorita de desconectar después del trabajo?',
  '¿Cuál es tu postre favorito?',
  '¿Qué idioma te gustaría aprender?',
  '¿Cuál es tu color favorito?',
  '¿Qué app de streaming usas más?',
  '¿Cuál es tu comida favorita para el desayuno?',
  '¿Qué mascota tienes o te gustaría tener?',
  '¿Cuál es tu estación del año favorita?',
  '¿Qué actividad haces los fines de semana?',
  '¿Cuál es tu restaurante favorito?',
  '¿Qué instrumento musical te gustaría tocar?',
  '¿Cuál es tu recuerdo favorito de la niñez?',
  '¿Qué te hace reír sin falta?',
  '¿Cuál es tu red social favorita?',
  '¿Qué talento oculto tienes?',
  '¿Cuál es tu palabra favorita en español?',
  '¿Qué serie o dibujos animados marcaron tu infancia?',
  '¿Cuál es tu forma favorita de hacer ejercicio?',
  '¿Qué olor te trae buenos recuerdos?',
  '¿Cuál es tu bebida favorita (sin alcohol)?',
  '¿Qué ciudad te gustaría visitar antes de morir?',
  '¿Cuál fue el mejor concierto al que has ido?',
  '¿Qué comida no soportas?',
  '¿Cuál es tu hobby favorito?',
  '¿Qué canción te levanta el ánimo siempre?',
  '¿Cuál es tu app de productividad favorita?',
  '¿Qué te gustaría estudiar si volvieras a empezar?',
  '¿Cuál es tu estilo de música favorito?',
  '¿Prefieres la playa al amanecer o al atardecer?',
  '¿Cuál es tu comida rápida favorita?',
  '¿Qué es lo primero que haces al despertar?',
  '¿Cuál es tu frase o refrán favorito?',
  '¿Qué te hubiera gustado ser de niño?',
  '¿Cuál es tu equipo deportivo favorito?',
  '¿Qué es lo que más valoras en un compañero de trabajo?',
  '¿Cuál ha sido tu mejor viaje?',
  '¿Qué comida dominicana extrañas más cuando viajas?',
  '¿Cuál es tu postre navideño favorito?',
  '¿Qué te gusta hacer para relajarte un fin de semana lluvioso?',
  '¿Cuál es tu personaje de película favorito?',
  '¿Qué juego de mesa te gusta más?',
  '¿Cuál es tu meta personal para este año?',
  '¿Qué costumbre dominicana te representa más?',
  '¿Prefieres el carro o la moto?',
  '¿Cuál es tu comida picante favorita?',
  '¿Qué canción cantarías en un karaoke sin pena?',
  '¿Cuál es tu app favorita para escuchar música?',
  '¿Qué es lo que más te gusta de tu trabajo?',
  '¿Cuál fue tu primer celular?',
  '¿Qué serie estás viendo actualmente?',
  '¿Cuál es tu forma favorita de empezar la semana?',
];

export const FRASES_DEL_DIA: string[] = [
  'El progreso, no la perfección.',
  'Un pequeño paso hoy vale más que un plan perfecto mañana.',
  'La constancia le gana al talento cuando el talento no es constante.',
  'Equipo que se comunica, equipo que avanza.',
  'Celebra lo pequeño — ahí se construye lo grande.',
  'Nadie llega lejos solo.',
  'Hoy es un buen día para aprender algo nuevo.',
  'La actitud es la diferencia entre un problema y un reto.',
  'El descanso también es parte del trabajo bien hecho.',
  'Pregunta cuando no sepas — así se crece.',
  'Cada bitácora enviada es un paso más cerca de la meta.',
  'La claridad de hoy evita el caos de mañana.',
  'Un gracias a tiempo vale más de lo que parece.',
  'Lo simple, bien hecho, gana a lo complicado a medias.',
  'El buen humor también es productividad.',
  'Ayudar a un compañero es invertir en el equipo.',
  'La curiosidad es el mejor combustible profesional.',
  'Los errores de hoy son la experiencia de mañana.',
  'Un equipo fuerte se nota en los días difíciles.',
  'Empieza donde estás, con lo que tienes.',
];
