-- AlterEnum
ALTER TYPE "TipoNovedad" ADD VALUE 'EXITO';
ALTER TYPE "TipoNovedad" ADD VALUE 'COSA_BUENA';
ALTER TYPE "TipoNovedad" ADD VALUE 'TARDANZA';
ALTER TYPE "TipoNovedad" ADD VALUE 'PERMISO';
ALTER TYPE "TipoNovedad" ADD VALUE 'NO_CUMPLIMIENTO';
ALTER TYPE "TipoNovedad" ADD VALUE 'EVENTO';
ALTER TYPE "TipoNovedad" ADD VALUE 'NOTA';
